// Product CRUD
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

// Create PRODUCT
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

// Edit Product
export const EDIT_PRODUCT = 'EDIT_PRODUCT'

// Delete Product
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'

// Settings
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY'
