// Product CRUD
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

// Create PRODUCT
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

// Edit Product
export const EDIT_PRODUCT = 'EDIT_PRODUCT'

// Delete Product
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_SAVE_USER_SHIPPING_INFO = 'CART_SAVE_USER_SHIPPING_INFO'

export const CART_ADD_ITEM_TO_DB_REQUEST = 'CART_ADD_ITEM_TO_DB_REQUEST'
export const CART_REMOVE_ITEM_TO_DB_REQUEST = 'CART_REMOVE_ITEM_TO_DB_REQUEST'
export const UPDATE_CART_ITEM_TO_DB_REQUEST = 'UPDATE_CART_ITEM_TO_DB_REQUEST'
export const MOVE_CART_ITEM_TO_DB_REQUEST = 'MOVE_CART_ITEM_TO_DB_REQUEST'

export const CART_ADD_ITEM_TO_DB = 'CART_ADD_ITEM_TO_DB'
export const CART_REMOVE_ITEM_TO_DB = 'CART_REMOVE_ITEM_TO_DB'
export const UPDATE_CART_ITEM_TO_DB = 'UPDATE_CART_ITEM_TO_DB'
export const MOVE_CART_ITEM_TO_DB = 'MOVE_CART_ITEM_TO_DB'

export const CART_ADD_ITEM_TO_DB_FAIL = 'CART_ADD_ITEM_TO_DB_FAIL'
export const CART_REMOVE_ITEM_TO_DB_FAIL = 'CART_REMOVE_ITEM_TO_DB_FAIL'
export const UPDATE_CART_ITEM_TO_DB_FAIL = 'UPDATE_CART_ITEM_TO_DB_FAIL'
export const MOVE_CART_ITEM_TO_DB_FAIL = 'MOVE_CART_ITEM_TO_DB_FAIL'

// Settings
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY'

// Authentication
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

// Register Account
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// User Info
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

// Update User Info
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// Update Password
export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL'

// Update Language Settings
export const USER_UPDATE_LANGUAGE_REQUEST = 'USER_UPDATE_LANGUAGE_REQUEST'
export const USER_UPDATE_LANGUAGE_SUCCESS = 'USER_UPDATE_LANGUAGE_SUCCESS'
export const USER_UPDATE_LANGUAGE_FAIL = 'USER_UPDATE_LANGUAGE_FAIL'

// Create order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_SESSION_REQUEST = 'ORDER_SESSION_REQUEST'
export const ORDER_SESSION_SUCCESS = 'ORDER_SESSION_SUCCESS'
export const ORDER_SESSION_FAIL = 'ORDER_SESSION_FAIL'

// Get User Orders
export const GET_USER_ORDER_REQUEST = 'GET_USER_ORDER_REQUEST'
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS'
export const GET_USER_ORDER_FAIL = 'GET_USER_ORDER_FAIL'
